name: Cpp-Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: cmake -S ./cpp -B build -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build --config Debug --target all --

      - name: test
        run: cd build && ctest

      - uses: codecov/codecov-action@v3
        with: 
          working-directory: ./cpp

  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: configure
        run: cmake -S ./cpp -B build -DCMAKE_BUILD_TYPE=Release

      - name: build
        run: cmake --build build --config Release --target all --

      - name: test
        run: cd build && ctest

      - uses: codecov/codecov-action@v3
        with: 
          working-directory: ./cpp